<bwa_align.mk

# This program uses threads, so we use only one process
NPROC=1

BWA_ALIGN_TARGETS=`{find -L ../data/ -name '*.fastq.gz' \
	| sed \
		-e 's#\.\./data/#../results/bwa_align/#g' \
		 -e 's#_L001_R[12]_001\.fastq\.gz$#.sam#g' \
	| sort -u \
}

bwa_align:V: $BWA_ALIGN_TARGETS

../results/bwa_align/%.sam:	../data/%_L001_R1_001.fastq.gz	../data/%_L001_R2_001.fastq.gz
	mkdir -p `dirname $target`
	bwa mem \
		-t $THREADS \
		$REFERENCE \
		$prereq \
		> $target
